### ISSUE TITLE
这个代码拉下来都跑不了，libcef.dll chromeelf.dll都是用本机的

### ISSUE THREAD

**Issue by jirotao** [JelinYao/MyChrome#2]
这个代码拉下来都跑不了，libcef.dll chromeelf.dll都是用本机的

**Comment by JelinYao** [comment]
代码不能跑起来还是你自己不会搞？二进制文件很大的，全都压缩了放到了release里，去下载然后放进去。你本机的libcef和代码用的版本不一样当然不行的。

**Comment by shenxiaolong-code** [comment]
作为演示性代码，没有必要使用太多依赖，否则别人的机器可能跑不起来，除非自带完整的依赖，但这很多情况下又不现实。
演示libcef建议只带libcef的东西，我的开发机上DuiLib工程就编译不过，缺少预编译的PCH文件。
而且尽量别搞预编译，演示性的项目要以尽量保证别人的环境下能够跑起来为最低要求。

**Comment by jirotao** [comment]
> 代码不能跑起来还是你自己不会搞？二进制文件很大的，全都压缩了放到了release里，去下载然后放进去。你本机的libcef和代码用的版本不一样当然不行的。

你找个正常的环境跑跑试试，依赖的东西太多

**Comment by JelinYao** [comment]
> 作为演示性代码，没有必要使用太多依赖，否则别人的机器可能跑不起来，除非自带完整的依赖，但这很多情况下又不现实。
> 演示libcef建议只带libcef的东西，我的开发机上DuiLib工程就编译不过，缺少预编译的PCH文件。
> 而且尽量别搞预编译，演示性的项目要以尽量保证别人的环境下能够跑起来为最低要求。

VS的高版本是没法兼容低版本的，我电脑只安装了VS2017，低版本VS编译你可以自己动手去配置。另外，这个工程不是演示cef，主要是cef集成到Duilib界面库中实现的一个简单浏览器。
