### ISSUE TITLE
您好，xml文件可以提供下吗？

### ISSUE THREAD

**Issue by LoveChina-3000** [JelinYao/MyChrome#3]
您好，xml文件可以提供下吗?学习下，谢谢

**Comment by JelinYao** [comment]
![image](https://user-images.githubusercontent.com/7205249/86725908-aa01f280-c05c-11ea-8e59-335841c08c90.png)
douz
xml配置以及二进制文件都在Release里面，下载就可以看到了。

**Comment by yetengfei** [comment]
您好，Release只有3个lib文件呢，
![image](https://user-images.githubusercontent.com/8185255/86857915-272b7700-c0f2-11ea-9e0b-e12470b9c4c7.png)

**Comment by LoveChina-3000** [comment]
在1.0的里面 ，谢谢啦
