### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by MX-Qulin** [JelinYao/MyChrome#4]
VS2015无法编译,报错.

**Comment by JelinYao** [comment]
是的，目前上传的代码是用VS2017编译的。建议下载libcef代码，编译出lib，替换下就可以了。

**Comment by MX-Qulin** [comment]
请问 支持<audio>,<video>或者flash吗?
能缩放页面吗?

**Comment by JelinYao** [comment]
1、2704是Chrome16年发布的最后一个支持XP的版本，支持flash。
2、缩放页面功能今天更新代码加上。

**Comment by MX-Qulin** [comment]
好的:) 下载支持的吧? 能支持下VS2015编译吗?我电脑上只有VS2015┭┮﹏┭┮🙁

**Comment by MX-Qulin** [comment]
> 是的，目前上传的代码是用VS2017编译的。建议下载libcef代码，编译出lib，替换下就可以了。
但是其他的代码不用编译吗?

**Comment by JelinYao** [comment]
1、已更新代码，支持网页缩放，目前只能焦点在主窗口上时滚动鼠标缩放，时间仓促后续完善，分支chrome3809。
2、因为我的电脑没有VS2015没法给你编译（安装VS太费劲了，尤其是我已经装了十几G的VS2017），你可以自己用VS2015编译，也没那么难。

**Comment by MX-Qulin** [comment]
好的,我再试试.
但是VS2015好像会报错啊┭┮﹏┭┮
Anyway, Thankyou for helping.

**Comment by MX-Qulin** [comment]
> 1、2704是Chrome16年发布的最后一个支持XP的版本，支持flash。

所以我用现在3809的branch,加入2704的CEF lib可以支持flash并正常运行吗?

**Comment by MX-Qulin** [comment]
@JelinYao  怎么改UI啊😏

**Comment by MX-Qulin** [comment]
@JelinYao 额 报错了
```
C2039	“unique_ptr”: 不是“std”的成员 (编译源文件 ThirdPart\MiscUI\WaterEffect.cpp)	MyChrome	d:\mychrome-chrome3809\mychrome-chrome3809\src\mychrome\thirdpart\miscui\WaterEffect.h	148	1	生成
```

**Comment by JelinYao** [comment]
> @JelinYao 额 报错了
> 
> ```
> 1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v141_xp (Platform Toolset = 'v141_xp') cannot be found. To build using the v141_xp build tools, please install v141_xp build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
> ```
 错误信息：please install v141_xp build tools，因为你没有安装VS2015的XP工具包。如果不考虑支持XP，可以不用安装，修改项目编译属性为不带_xp的。如果要支持XP，就下载XP工具包。
![image](https://user-images.githubusercontent.com/7205249/87623121-42802d00-c757-11ea-946e-02cb4729438d.png)

**Comment by JelinYao** [comment]
> > 1、2704是Chrome16年发布的最后一个支持XP的版本，支持flash。
> 
> 所以我用现在3809的branch,加入2704的CEF lib可以支持flash并正常运行吗?

不行，2704和3809用的libcef代码不一样，生成的lib库也不一样。master分支Chrome版本是2704，今天尝试把缩放代码移植到master分支。

**Comment by MX-Qulin** [comment]
> 
> 
> > > 1、2704是Chrome16年发布的最后一个支持XP的版本，支持flash。
> > 
> > 
> > 所以我用现在3809的branch,加入2704的CEF lib可以支持flash并正常运行吗?
> 
> 不行，2704和3809用的libcef代码不一样，生成的lib库也不一样。master分支Chrome版本是2704，今天尝试把缩放代码移植到master分支。

好的,谢谢

**Comment by MX-Qulin** [comment]
> 
> 
> > @JelinYao 额 报错了
> > ```
> > 1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v141_xp (Platform Toolset = 'v141_xp') cannot be found. To build using the v141_xp build tools, please install v141_xp build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
> > ```
> 
> 错误信息：please install v141_xp build tools，因为你没有安装VS2015的XP工具包。如果不考虑支持XP，可以不用安装，修改项目编译属性为不带_xp的。如果要支持XP，就下载XP工具包。
> ![image](https://user-images.githubusercontent.com/7205249/87623121-42802d00-c757-11ea-946e-02cb4729438d.png)

这个我解决了,谢谢您
但是现在好像watereffect.h和watereffect.cpp有问题了
![截图](https://user-images.githubusercontent.com/39642357/87624641-cee01f00-c75a-11ea-99d2-80c30fc150cf.JPG)

**Comment by MX-Qulin** [comment]
好像要加watereffect.h要加上```#include <memory>```?
#5

**Comment by MX-Qulin** [comment]
好的,我现在编译完了,把83.4.2的libcef.dll和chrome_elf.dll放到了release目录下,但是运行不了(无界面弹出) @JelinYao

**Comment by JelinYao** [comment]
1、“但是现在好像watereffect.h和watereffect.cpp有问题了”，这两个文件没什么用，可以删了。
2、“,把83.4.2的libcef.dll和chrome_elf.dll放到了release目录下”，Chrome浏览器的dll和libcef不一样，肯定用不了，去右侧Release下载对应的Release包，然后把里面的文件都复制到你的生成目录下面，然后重新编译下。
![image](https://user-images.githubusercontent.com/7205249/87633382-e4127900-c76d-11ea-93cc-4e42176ea428.png)

**Comment by MX-Qulin** [comment]
> 
> 
> 1、“但是现在好像watereffect.h和watereffect.cpp有问题了”，这两个文件没什么用，可以删了。
> 2、“,把83.4.2的libcef.dll和chrome_elf.dll放到了release目录下”，Chrome浏览器的dll和libcef不一样，肯定用不了，去右侧Release下载对应的Release包，然后把里面的文件都复制到你的生成目录下面，然后重新编译下。
> ![image](https://user-images.githubusercontent.com/7205249/87633382-e4127900-c76d-11ea-93cc-4e42176ea428.png)

ok

**Comment by MX-Qulin** [comment]
好像不能缩放???(可能我操作不对) 
我已clone了最新版本,但是ctrl+滚轮或者(+,-键)都没用
"焦点在主窗口上时滚动鼠标缩放"不太理解...😐

**Comment by MX-Qulin** [comment]
@JelinYao  能讲一下您是如何实现DownloadHandler的吗?我好像遇到问题了😢

**Comment by JelinYao** [comment]
1、主窗口活的焦点才可以滚动确实不太友好，目前只是验证网页缩放功能，后面花时间改一下。
2、去看看MyChrome\Libcef\include\cef_download_handler.h这个文件，实现下CefDownloadHandler的两个虚函数，拿到CefDownloadItemCallback对象就可以控制下载过程：取消、暂停、继续……多看看libcef头文件，里面的注释很有帮助的。思路大概是这样，我还没处理下载的回调。

**Comment by MX-Qulin** [comment]
> 1、主窗口活的焦点才可以滚动确实不太友好，目前只是验证网页缩放功能，后面花时间改一下。
> 2、去看看MyChrome\Libcef\include\cef_download_handler.h这个文件，实现下CefDownloadHandler的两个虚函数，拿到CefDownloadItemCallback对象就可以控制下载过程：取消、暂停、继续……多看看libcef头文件，里面的注释很有帮助的。思路大概是这样，我还没处理下载的回调。

好的,谢谢.

我再问一下您是怎么操作滚动的?(好像我无论怎么滚鼠标都不会缩放😹)

**Comment by JelinYao** [comment]
> > 1、主窗口活的焦点才可以滚动确实不太友好，目前只是验证网页缩放功能，后面花时间改一下。
> > 2、去看看MyChrome\Libcef\include\cef_download_handler.h这个文件，实现下CefDownloadHandler的两个虚函数，拿到CefDownloadItemCallback对象就可以控制下载过程：取消、暂停、继续……多看看libcef头文件，里面的注释很有帮助的。思路大概是这样，我还没处理下载的回调。
> 
> 好的,谢谢.
> 
> 我再问一下您是怎么操作滚动的?(好像我无论怎么滚鼠标都不会缩放😹)

网页打开后，鼠标点击标题栏，让主窗口活的焦点，然后滚动鼠标滚轮。（可以加缩放按钮操作，后续完善）

**Comment by MX-Qulin** [comment]
> 
> 
> > > 1、主窗口活的焦点才可以滚动确实不太友好，目前只是验证网页缩放功能，后面花时间改一下。
> > > 2、去看看MyChrome\Libcef\include\cef_download_handler.h这个文件，实现下CefDownloadHandler的两个虚函数，拿到CefDownloadItemCallback对象就可以控制下载过程：取消、暂停、继续……多看看libcef头文件，里面的注释很有帮助的。思路大概是这样，我还没处理下载的回调。
> > 
> > 
> > 好的,谢谢.
> > 我再问一下您是怎么操作滚动的?(好像我无论怎么滚鼠标都不会缩放😹)
> 
> 网页打开后，鼠标点击标题栏，让主窗口活的焦点，然后滚动鼠标滚轮。（可以加缩放按钮操作，后续完善）

可以了😂 有点操作难度:)
