### ISSUE TITLE
duilib chrome窗口拖移分离合并也可以把

### ISSUE THREAD

**Issue by fangniuge** [JelinYao/MyChrome#7]
作者写的博文很牛，demo也很厉害。我记得以前关注过一个哥们写的duilib仿chrome多标签浏览器也很不错。libcef内核全仿chrome支持窗口拖移分离合并。码云地址：https://gitee.com/bencloud/mul-drag-tab-cef-browser   大家可以研究下

**Comment by JelinYao** [comment]
看了一下，那个就放了一个二进制，没什么意义。

**Comment by iworkcloud** [comment]
+1

**Comment by iworkcloud** [comment]
不知能否实现一启动同时打开多个地址，并且在不同的窗口里，而不是现在在一个窗口的不同Tab里。
